### ISSUE TITLE
How do I get all group info? Name + Group Id

### ISSUE THREAD

**Issue by milkkyywayz** [milkkyywayz/SimpleWhatsappBot#1]
How do I get that? I have tried several ways, but have not been able to get it.

Maybe someone can help me? It was very helpful for me. ☺

**Comment by danendracoding** [comment]
> How do I get that? I have tried several ways, but have not been able to get it.
> 
> Maybe someone can help me? It was very helpful for me. ☺

In the :

```
else if(connection === 'open') {
    // Add Code
    return;
}
```

Add Code :

```
let getGroups = await sock.groupFetchAllParticipating();
let groups = Object.values(await sock.groupFetchAllParticipating());
for (let group of groups) {
    console.log("Group Id: " + group.id + " || Group Name: " + group.subject);
}
```

**Comment by milkkyywayz** [comment]
@danendracoding Wow... Thanks bro, Works well.

**Comment by milkkyywayz** [comment]
@danendracoding  Wow... Thanks bro, Works well.
